x-env: &env
  environment:
    - ADMIN_PASSWORD=password
    - ADMIN_USER=admin@example.com
    - ALLOWED_HOSTS=localhost
    - AUTHENTICATION_BACKENDS=country_workspace.security.backends.AnyUserAuthBackend
    - CACHE_URL=redis://valkey/1
    - CSRF_COOKIE_SECURE=False
    - CSRF_TRUSTED_ORIGINS=http://localhost:8000
    - DATABASE_URL=postgres://db:password@db:5432/booking
    - DEBUG=true
    - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    - POSTGRES_DB=booking
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=db
    - SECRET_KEY=sensitive-secret-key
    - SOCIAL_AUTH_REDIRECT_IS_HTTPS=false

x-common: &common
  build:
    context: .
    dockerfile: docker/Dockerfile
    target: dist
  restart: always
  depends_on:
    db:
      condition: service_healthy


services:
  backend:
    <<:  [*common, *env]
    ports:
      - 8000:8000
    command: run
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5


  valkey:
    image: valkey/valkey:alpine3.21
    <<:  [*env]
    restart: always


  db:
    image: postgres:15
    <<:  [*env]
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "db", "-d", "booking" ]
      start_period: 5s
      start_interval: 1s
      interval: 5s
      timeout: 4s
      retries: 5
