x-env: &env
  environment:
    - ADMIN_PASSWORD=password
    - ADMIN_USER=admin@example.com
    - ALLOWED_HOSTS=localhost
    - AUTHENTICATION_BACKENDS=country_workspace.security.backends.AnyUserAuthBackend
    - CACHE_URL=redis://valkey/1
    - CSRF_COOKIE_SECURE=False
    - CSRF_TRUSTED_ORIGINS=http://localhost:8000
    - DATABASE_URL=postgres://db:password@db:5432/booking
    - DJANGO_SETTINGS_MODULE=booking.config.settings
    - DEBUG=true
    - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    - POSTGRES_DB=booking
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=db
    - SECRET_KEY=sensitive-secret-key
    - SOCIAL_AUTH_REDIRECT_IS_HTTPS=false


services:
  backend-latest:
    <<:  [*env]
    image: saxix/booking:latest
    ports:
      - 8000:8000
    command: run
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: [prd]

  backend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      cache_from:
        - saxix/booking:latest
      target: dist
    <<:  [*env]
    restart: always
    profiles: ['', dev]
    depends_on:
      - db
      - valkey
    ports:
      - 8000:8000
    develop:
      watch:
      - path: ./uv.lock
        action: rebuild
      - path: ./src/booking
        target: /venv/lib/python3.12/site-packages/booking
        ignore:
          - theme/static_src
        action: sync+restart
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5


  valkey:
    image: valkey/valkey:alpine3.21
    platform: linux/amd64
    <<:  [*env]
    restart: always
    profiles: ['', dev, prd]


  db:
    image: postgres:15
    platform: linux/amd64
    <<:  [*env]
    restart: always
    profiles: ['', dev, prd]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "db", "-d", "booking" ]
      start_period: 5s
      start_interval: 1s
      interval: 5s
      timeout: 4s
      retries: 5
