copyright: Copyright &copy; 2020-2024 ACME Corp.
dev_addr: 127.0.0.1:8001
docs_dir: docs/src
edit_uri: 'blob/develop/docs/'
repo_url: https://github.com/saxix/booking
site_author: ACME
site_description: ""
site_dir: ./~build/docs
site_name: Booking
site_url: https://saxix.github.io/saxix/booking/
strict: false
exclude_docs: |
  _docs/*
  _hooks/*
  _includes/*
  _scripts/*
  ~*

markdown_extensions:
  - admonition
  - pymdownx.magiclink

theme:
  name: "material"
  color_mode: auto
#  favicon: img/favicon.ico
#  logo: img/logo.png
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - django
  user_color_mode_toggle: true
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohidex
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  extra:
    version:
      provider: mike
      alias: true
#  palette:
#    # Palette toggle for light mode
#    - scheme: default
#      primary: light blue
#      media: "(prefers-color-scheme: light)"
#      toggle:
#        icon: material/weather-sunny
#        name: Switch to dark mode
#
#    # Palette toggle for dark mode
#    - scheme: slate
#      primary: light blue
#      media: "(prefers-color-scheme: dark)"
#      toggle:
#        icon: material/weather-night
#        name: Switch to light mode

plugins:
  - mkdocstrings:
      default_handler: python
  - awesome-pages
  - search

watch:
  - src/
