# Generated by Django 4.2.17 on 2024-12-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="services",
            field=models.ManyToManyField(blank=True, to="booking.service"),
        ),
    ]
