# Generated by Django 4.2.17 on 2024-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_service_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("start_date__lte", models.F("end_date"))), name="start_date_lte_end_date"
            ),
        ),
    ]
