# Generated by Django 4.2.17 on 2025-01-15 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_user_options_user_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="car",
            field=models.ForeignKey(
                help_text="Car related to the booking.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.car",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                help_text="The customer who owns the booking.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(help_text="End date of the booking."),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(help_text="Start date of the booking."),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Total price of the booking.", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, help_text="Short description of the car.", null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.CharField(blank=True, help_text="Image of the car.", max_length=255),
        ),
        migrations.AlterField(
            model_name="car",
            name="in_service",
            field=models.BooleanField(default=True, help_text="Whether the car is in service."),
        ),
        migrations.AlterField(
            model_name="car",
            name="max_passenger",
            field=models.PositiveIntegerField(help_text="Maximum number of passengers allowed in the car."),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(help_text="Model of the car.", max_length=255),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate",
            field=models.CharField(default="", help_text="Plate of the car.", max_length=10),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, help_text="Daily price of the car.", max_digits=10),
        ),
        migrations.AlterField(
            model_name="car",
            name="services",
            field=models.ManyToManyField(blank=True, help_text="Services related to the car.", to="booking.service"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.TextField(help_text="Comment of the feedback."),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Feedback creation data."),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="customer",
            field=models.ForeignKey(
                help_text="The customer who owns the booking.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="property",
            field=models.ForeignKey(
                help_text="Car related to the booking.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="booking.car",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveIntegerField(help_text="Rating of the feedback."),
        ),
    ]
