# Generated by Django 4.2.17 on 2025-01-16 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_booking_car_alter_booking_customer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
