# Generated by Django 4.2.17 on 2025-01-16 12:18
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_delete_feedback"),
    ]

    operations = [
        BtreeGistExtension(),
    ]
