# Generated by Django 4.2.17 on 2025-01-21 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_remove_booking_not_start_date_eq_end_date_and_start_date_gt_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address",
            field=models.TextField(
                blank=True, default="", help_text="Indirizzo in caso di conseghna a domicilio", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="modalita",
            field=models.IntegerField(
                choices=[(0, "Prelievo in sede"), (1, "Consegna a domicilio"), (2, "Conducente")],
                default=0,
                help_text="Modality of the booking.",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="car",
            field=models.ForeignKey(
                help_text="Veicolo in noleggio",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.car",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                help_text="Cliente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(help_text="Data fine noleoggio"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(help_text="Data inizio noleoggio"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, help_text="PRezzo totale.", max_digits=10),
        ),
    ]
